# Varibles
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
content-type: application/json

{
  "name": "Test Room",
  "description": "This is a test room"
}

###

# @roomId = {{getRooms.response.body.$.[0].id}}
@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create room
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
content-type: application/json

{
  "question": "What is the context of X within Y?"
}
